# test user
from bettercrative import bcrypt, db, create_app
from bettercrative.models import User, Classroom, Answer, Quiz, Question
app = create_app()
app.app_context().push()

test_password = bcrypt.generate_password_hash('password').decode('utf-8')
testuser = User(username='user', email='user@email.com', password=test_password)
db.session.add(testuser)
# two classrooms
classroom_1 = Classroom(name='CSCI 497')
testuser.classrooms.append(classroom_1)
classroom_2 = Classroom(name='MATH 341')
testuser.classrooms.append(classroom_2)
# two quizzes, each with 2 MC questions and 4 answers to each
quiz_1 = Quiz(name='Computer Science Quiz')
question_1 = Question(name='Question 1', content='Who is the best CS professor?', category='Multiple Choice')
quiz_1.questions.append(question_1)
answer_1_1 = Answer(content='Hao', correct=True)
answer_1_2 = Answer(content='Clauson', correct=False)
answer_1_3 = Answer(content='Meehan', correct=False)
answer_1_4 = Answer(content='Yudong', correct=False)
question_1.answers.append(answer_1_1)
question_1.answers.append(answer_1_2)
question_1.answers.append(answer_1_3)
question_1.answers.append(answer_1_4)
question_2 = Question(name='Question 2', content='Which is the best department at Western?', category='Multiple Choice')
quiz_1.questions.append(question_2)
answer_2_1 = Answer(content='Psychology', correct=False)
answer_2_2 = Answer(content='Education', correct=False)
answer_2_3 = Answer(content='History', correct=False)
answer_2_4 = Answer(content='Computer Science', correct=True)
question_2.answers.append(answer_2_1)
question_2.answers.append(answer_2_2)
question_2.answers.append(answer_2_3)
question_2.answers.append(answer_2_4)
testuser.quizzes.append(quiz_1)
quiz_2 = Quiz(name='Math Quiz')
question_1 = Question(name='Question 1', content='What is 2 + 2?', category='Multiple Choice')
quiz_2.questions.append(question_1)
answer_1_1 = Answer(content='5', correct=False)
answer_1_2 = Answer(content='-609', correct=False)
answer_1_3 = Answer(content='4', correct=True)
answer_1_4 = Answer(content='37', correct=False)
question_1.answers.append(answer_1_1)
question_1.answers.append(answer_1_2)
question_1.answers.append(answer_1_3)
question_1.answers.append(answer_1_4)
question_2 = Question(name='Question 1', content='What is the square root of 49?', category='Multiple Choice')
quiz_2.questions.append(question_2)
answer_2_1 = Answer(content='3i', correct=False)
answer_2_2 = Answer(content='7', correct=True)
answer_2_3 = Answer(content='100', correct=False)
answer_2_4 = Answer(content='5.67', correct=False)
question_2.answers.append(answer_2_1)
question_2.answers.append(answer_2_2)
question_2.answers.append(answer_2_3)
question_2.answers.append(answer_2_4)
testuser.quizzes.append(quiz_2)
# Add both quizzes to first classroom, second quiz to second classroom, make first active in c1 and second active in c2
classroom_1.added_quizzes.append(quiz_1)
classroom_1.added_quizzes.append(quiz_2)
classroom_1.active_quiz = quiz_1.id
quiz_1.active = True
classroom_2.added_quizzes.append(quiz_1)
classroom_2.active_quiz = quiz_2.id
quiz_2.active = True
db.session.commit()
