"""empty message

Revision ID: 10ab2a7691d5
Revises: 
Create Date: 2020-02-11 21:11:16.832320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10ab2a7691d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('classroom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classroom_Name', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=15), nullable=False),
    sa.Column('classroom_owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_Name', sa.Integer(), nullable=False),
    sa.Column('questions', sa.String(length=100), nullable=True),
    sa.Column('answers', sa.String(length=200), nullable=True),
    sa.Column('quiz_owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz')
    op.drop_table('classroom')
    op.drop_table('user')
    # ### end Alembic commands ###
